[build]
default-target = "arm-unknown-linux-gnueabihf"    # use this target if none is explicitly provided
pre-build = [ 
    "apt update",
    "apt install libasound-dev -y",
    "apt install libasound2-dev -y"
]
