[build]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt-get -y install gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf libasound2-dev:armhf pkg-config"
]

[build.env]
passthrough = [
    "PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig",
    "PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf",
    "PKG_CONFIG_ALLOW_CROSS=1",
    "CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc"
]