[build]
default-target = "arm-unknown-linux-gnueabihf"    # use this target if none is explicitly provided
pre-build = [ 
    "apt-get update",
    "apt-get install libasound-dev -y",
    "apt-get install libasound2-dev -y"
]
